## Comments to Hatsune's Jupyter notebook on focal length measurement

Notebook outline:

0. Useful Python resources
1. General comments and recommendation regarding coding style
2. Comments to individual screenshots
3. Summary

*Note:* since your English is fairly well, I highly recommend to use English-language resources (which are much more ubiquitous than in other languagues; besides English is the "native" language of the programming world). The programming vocabulary is relative small and easy to learn. I also urge you to write code comments in English.

### 0. Useful Python resources

#### Documentation
1. [Python documentation](https://docs.python.org/3/index.html)\
   [The Python Standard Library](https://docs.python.org/3/library/index.html)\
   [Built-in Functions](https://docs.python.org/3/library/functions.html)
2. [NumPy documentation](https://numpy.org/doc/stable/index.html)\
   I particulary recommend to read [NumPy user guide](https://numpy.org/doc/stable/user/index.html#user),
   at least [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
   and [NumPy fundamentals](https://numpy.org/doc/stable/user/basics.html)
   (highly recommended though a bit more advanced is [Advanced NumPy](https://scipy-lectures.org/advanced/advanced_numpy/)).\
    The reference manual whcih details functions, modules, and objects included in NumPy, describing what they are and what they do: [NumPy Reference](https://numpy.org/doc/stable/reference/index.html#reference)
3. [SciPy documentation](https://docs.scipy.org/doc/scipy/index.html)

#### Online resources
1. [Real Python Tutorials](https://realpython.com/) - highly useful, especially for beginners
2. [Stack Oveflow](https://stackoverflow.com/) - should be used to find answers to coding (and other "computational") question instead of general search engines like Google, etc. (tough serching with Google often find answers at Stack Oveflow)
3. Many Python online courses can be found on the MOOC platforms like [Coursera](https://www.coursera.org/),
   [edX](https://www.edx.org/) and just on [YouTube](https://www.youtube.com/). Think about taking some free Python course for beginners.\
   For example: [Python for beginners](https://www.coursera.org/search?query=python%20for%20beginners&)
   (I guess majority of the courses have Japanese subtitles)

#### Books (there are a lot of books, I give  a reference just to one free book and to one printed book):
1. [Python Notes for Professionals](https://www.dbooks.org/python-notes-for-professionals-5591650063/)
   Don't be scared by the word "Professionals" - actually it is a detailed reference guide with a lot 
   of examples. I find it much more convenient to use than the Python documentation cited above.
2. After you learn Python a bit more, you'll be able to enjoy reading this book:\
   Python Distilled by David Beazley (2021)   

### General comments and recommendations regarding coding style

The Python code conventions are summarized in [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/#id26). Following these conventions greately improve code readability and simplify code writing.

In relation to your code, I'd like to emphaisize a few basic conventions:
1. [Whitespace in Expressions and Statements](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements) - please read.\
   So, for example, 
   `par, cov = curve_fit(ff,dist_list,width_list,sigma=ey)` should be written as:
   `par, cov = curve_fit(ff, dist_list, width_list, sigma=ey)`\
   If you start to follow this convention, after a while you'll notice that the code becomes easier to read and looking nicer; after a while this style will become your habbit.

2. [Naming Conventions](https://peps.python.org/pep-0008/#naming-conventions) - please read.

   * "Function names should be lowercase, with words separated by underscores as necessary to improve readability. Variable names follow the same convention as function names."\
   So, try to avoid using uppercase letters in variable (and function) names unless it is absolutely neccessary.

3. Use meaningful names for variable and functions. Names like 'ey' and 'ff' are not good - at the moment you
   can remember that `ey` means "error y" and `ff` - "fit function", but will you easily recall that in 1 year?
   And what about other people who may read your notebook?\
   So, instead `ey` you might use, for example, `yerr` or `y_err` (quite common names for such quantity),
   and instead of `def ff(...)` you might use `def parabola(...)`, since it is not just some function which will be used for fitting, but specific function - quadratic; later you might want to fit your data by other function (e.g. cubic) and define another function: `def cubic(...)`.\
   The same is true for function parameters: instead of naming them `a, b, c` you could have named them `a` (="amlitude"), `xmin`, `ymin` or (`x0` and `y0`) (since `a > 0` in your case, `b` and `c` are minimum x and y respectively; this suggestion is not very important for such a simple function, though generally it is better to give meaningful names to function parameters if they have specific meanings. 
   
4. It is a bad practice to encode variable type in its name, so instead of  `dist_list` and `width_list` 
   you might use something like `distance` and `peak_width`
   (it is a matter of personal taste, but since nowdays we do not have strick restrictions on the length of variable name, I often prefer to use full word rather than abbreviation unless the word is too long
    or has the commonly used abbreviation).
   
   
As concerns the code itself:
1. Try using NumPy arrays instead of lists for numbers. They are much more efficient and powerful than lists.\
   So, isntead of `ey = [4]*len(width_list)` it is much better to write `yerr = np.full(len(peak_width), 4.0)`
   (I wrote `4.0` to make this array of type `float`, another way of doing this is 
   `yerr = np.full(len(peak_width), 4, dtype=float)`
   (see [Array creation](https://numpy.org/doc/stable/user/basics.creation.html) for more on methods to create arrays). I'll give more examples below while commening on individual screenshots.
   
2. Do not use the `math` module if you are already using NumPy, i.e. instead of `math.sqrt(...)` use `np.sqrt(...)`

3. Use Python 3's f-Strings instead of old-style formatting: %-formatting and str.format().
   So, instead of `print("chi2 = {:7.3f}".format(chi2)` it is better to write 
   `print(f'chi2 = {chi2:7.3f}')` - it is more consise and easire to read 
   (BTW, why do you want `7.3f`? If you want just three decimal digits `print(f'chi2 = {chi2:.3f}')`)
   Actually, this can be written even shorter: `print(f'{chi2 = :.3f}')`\
   You can reed more about Python 3's f-Strings for exmaple [here](https://realpython.com/python-f-strings/)}

In [1]:
import numpy as np

Using Python 3's f-Strings:

In [2]:
chi2 = 12.345678

print(f'chi2 = {chi2:7.3f}')

chi2 =  12.346


In [3]:
# The shortest (preferable) way to output this:
print(f'{chi2 = :.3f}')

chi2 = 12.346


### Screenshot 1 - reading images

This is lengthy and clumsy. 

Should be made much shorter.

In [4]:
# Create a list of image indices
img_ind = [4848] + list(range(4851, 4865))   # line 1

img_ind

[4848,
 4851,
 4852,
 4853,
 4854,
 4855,
 4856,
 4857,
 4858,
 4859,
 4860,
 4861,
 4862,
 4863,
 4864]

In [5]:
# Create a list of image file names (use List Comprehension)
img_fnames = [f'IMG_{index}.CR3' for index in img_ind]   # line 2

img_fnames

['IMG_4848.CR3',
 'IMG_4851.CR3',
 'IMG_4852.CR3',
 'IMG_4853.CR3',
 'IMG_4854.CR3',
 'IMG_4855.CR3',
 'IMG_4856.CR3',
 'IMG_4857.CR3',
 'IMG_4858.CR3',
 'IMG_4859.CR3',
 'IMG_4860.CR3',
 'IMG_4861.CR3',
 'IMG_4862.CR3',
 'IMG_4863.CR3',
 'IMG_4864.CR3']

In [ ]:
# Read images into a list
rgb = []   # line 3

for img in img_fnames:   # line 4 
    with rawpy.imgread(img) as raw:    # line 5 
        rgb.append(raw.reprocessed(gamma=(1, 1), no_auto_bright=True, output_bps=16))  # line 6

So, all reading took just 6 lines of code.


Actually, since each image corresponds some shift (-25 mm, -20 mm, ..., +25 mm) it might be more convenient to read the images into a dictionary, rather then into a list:

In [6]:
# Create a list of shifts:
# -25, -20, .., -5, -4, -2, ... 4, 5, 10, ... 25
shifts = list(range(-25, 0, 5)) + list(range(-4, 6, 2)) + list(range(5, 30, 5))

shifts

[-25, -20, -15, -10, -5, -4, -2, 0, 2, 4, 5, 10, 15, 20, 25]

In [7]:
# Match the shifts and images:
# create a dictionary of image file names (use Dictionary Comprehension)
img_fnames = {key: f'IMG_{index}.CR3' for key, index in zip(shifts, img_ind)}

img_fnames

{-25: 'IMG_4848.CR3',
 -20: 'IMG_4851.CR3',
 -15: 'IMG_4852.CR3',
 -10: 'IMG_4853.CR3',
 -5: 'IMG_4854.CR3',
 -4: 'IMG_4855.CR3',
 -2: 'IMG_4856.CR3',
 0: 'IMG_4857.CR3',
 2: 'IMG_4858.CR3',
 4: 'IMG_4859.CR3',
 5: 'IMG_4860.CR3',
 10: 'IMG_4861.CR3',
 15: 'IMG_4862.CR3',
 20: 'IMG_4863.CR3',
 25: 'IMG_4864.CR3'}

As, you can see now that for each shift (that is a key in our dictionary) we have correspnding file name,
so we can easily get the name corresponding a given shift:

In [8]:
# Get a file name for shift = 4
img_fnames[4]

'IMG_4859.CR3'

*Note:* we can add 'mm' to keys, so they will become strings rather than numbers:

In [9]:
# Match the shifts and images:
# create a dictionary of image file names (use Dictionary Comprehension)
img_fnames = {f'{key}mm': f'IMG_{index}.CR3' for key, index in zip(shifts, img_ind)}

img_fnames

{'-25mm': 'IMG_4848.CR3',
 '-20mm': 'IMG_4851.CR3',
 '-15mm': 'IMG_4852.CR3',
 '-10mm': 'IMG_4853.CR3',
 '-5mm': 'IMG_4854.CR3',
 '-4mm': 'IMG_4855.CR3',
 '-2mm': 'IMG_4856.CR3',
 '0mm': 'IMG_4857.CR3',
 '2mm': 'IMG_4858.CR3',
 '4mm': 'IMG_4859.CR3',
 '5mm': 'IMG_4860.CR3',
 '10mm': 'IMG_4861.CR3',
 '15mm': 'IMG_4862.CR3',
 '20mm': 'IMG_4863.CR3',
 '25mm': 'IMG_4864.CR3'}

In [10]:
img_fnames['4mm']

'IMG_4859.CR3'

In [ ]:
# So now we can read images into a dictionary:
rgb = {}

for shift, img_file in img_fnames.items():
    with rawpy.imgread(img) as raw:
        rgb[shift] = raw.reprocessed(gamma=(1, 1), no_auto_bright=True, output_bps=16)

What is more convenient - list or dictionary depends on how these images will be further processed.

### Screenshot 2 - making image plots

Again, this is lengthy and clumsy.

Should be made much shorter and clearer.

Here we assume that images haven been read into a list `rgb`

All your `G_1.append(...)` lines should be replaced by just one:

In [ ]:
# Create a list of Green channels of the images
# Note: please choose a name you like, but meaningful (maybe `green_img`)
green_chan = [img[:, :, 1] for img in rgb]

To plot the images you should loop over sequence directly rather than using 
`for i in range(..)` and than referrering the sequence element by index `..[i]`:

In [ ]:
# To plot the images
for img in green_chan:
    ...
    plt.imshow(img, cmap='gray', norm=LogNorm())

# Note: LogNorm() intialize an onject of the LogNorm class; since we need just one such object
# it is better no initialize it before the loop:
norm = LogNorm()

for img in green_chan:
    ...
    plt.imshow(img, cmap='gray', norm=norm)

    

Much better way to make a list of plot titles:

In [11]:
# Note: there is no need to write '.0' but it is an old habbit to distinguish float variables from integers
# (if you write `ref_leo = 671` the variable `ref_leo` will be of `int` type )
ref_leo = 671.0  # mm
ref = ref_leo - 311.0 + 2.4 + 0.3  # mm

In [12]:
# just to show the type thing
tmp = 617

type(tmp)

int

In [13]:
# Here we use the list of shifts `shifts` created above:
plot_titles = [f'{ref + shift :.1f} mm' for shift in shifts]

plot_titles

['337.7 mm',
 '342.7 mm',
 '347.7 mm',
 '352.7 mm',
 '357.7 mm',
 '358.7 mm',
 '360.7 mm',
 '362.7 mm',
 '364.7 mm',
 '366.7 mm',
 '367.7 mm',
 '372.7 mm',
 '377.7 mm',
 '382.7 mm',
 '387.7 mm']

### Screenshot 3 - making histogramms¶

Again, you don't need a loop using range - loop directly over the sequence:

In [ ]:
# Instead of `G_sgr=[G_1[i][y1:y2, x1:x2] for i in range(len(G_1))]
# (now `G_1` is `green_chan`)
# Choose the image central part:
img_center = [img[y1:y2, x1:x2] for img in green_chan]

Make the plots as shown in the previous section ('Screensot 3').

### Screenshot 4 - making X-projections¶

Use the methods given above.

In [ ]:
# Instead of `X_Prj = ...`
# image projections on X-axis:
img_x = [np.sum(img, axis=0) for img in img_center]

In [14]:
# This is just ugly:
# for in in range(len(X_prj[1])):
#    X_prj_axis.append(i+x1)

# Create xscale:
x1 = 2100
x2 = 2800

x = np.arange(x1, x2)

In [15]:
# Just look at the first 10 points
x[:10]

array([2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109])

In [16]:
# Look at the last 10 points
x[-10:]

array([2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799])

In [17]:
len(x)

700

In [ ]:
# Check that the length of X-projections equals to the length of `x`
# (just to be sure - they must be the same by design)
len(img_x[0]) == len(x)

Make the plots as shown in the section 'Screensot 3'.

### Screenshot 5 - binning¶

This is done in an ansolutely wrong manner (in an ineffificent, C-like style using loops).\
**NumPy must be used!**

*Note: I do not see much use in such a binning for your task*

In [18]:
# Number of bins to sum over
nbins = 4

In [ ]:
img_x_binned = [np.sum(img.reshape(-1, nbins), axis=1) for img in img_x]

Explanation for the code above. The most efficient way of rebinning is to create a new dimension and summing over it:

In [19]:
a = np.arange(8)

a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
# Now let's rebin this array by summing over 4 elements.
# First: reshape it to (2, 4):
b = a.reshape(-1, 4)  # '-1' tells to automatically compute the first dimension

b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
b.shape

(2, 4)

In [22]:
# Second: sum over rows (axis=1) of the `b`:
np.sum(b, axis=1)

array([ 6, 22])

In [23]:
# Just in a single line of code:
np.sum(a.reshape(-1, nbins), axis=1)

array([ 6, 22])

*Note:* this method works when the length of the array is divisible by `nbins`, so the array can be reshaped:

In [24]:
# This will NOT work:
# (for exmaple. we would like to sum over 3 bins)
a.reshape(-1, 3)

ValueError: cannot reshape array of size 8 into shape (3)

In [25]:
# In such a case we might want at first to shrink the array (truncate several first or last elements).
# For example, this gives the maximum number divisible by 3 less than the array length:
n = 3 * (len(a) // 3)

n

6

In [26]:
# Then we can reshape by keeping first n-elements (removing the last (len(a) % 3) elements)
a[:n].reshape(-1, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
# Now we can sum in a single line of code:
np.sum(a[:n].reshape(-1, 3), axis=1)

array([ 3, 12])

To make xscale:

In [28]:
x_binned = np.arange(x1, x2, nbins)

x_binned[:5], x_binned[-5:]

(array([2100, 2104, 2108, 2112, 2116]), array([2780, 2784, 2788, 2792, 2796]))

In [ ]:
# Check that the length of rebinned X-projections equals to the length of `x_rebinned`
# (just to be sure - they must be the same by design)
len(img_x_binned[0]) == len(x_binned)

Make the plots as shown in the section 'Screensot 3'.

### Screenshot 6 - cumulative plots¶

Again, this is done in an ansolutely wrong manner (in an ineffificent, C-like style using loops).\
**NumPy must be used!**

*Note:* the word "cumulative" is spelled with 'l' (not 'r') (I know that the 'l' and 'r' sounds are often confused in Japanese.)

In [ ]:
max_idx = [np.argmax(img) for img in img_x_binned]
max_val = [img_x_binned[imax] for imax in max_idx]

In [ ]:
# Make a list of cumulative X-projections
cum_img_x_binned = [np.cumsum(img) for img in img_x_binned]

In [29]:
# See the description of `np.cumsum`:
help(np.cumsum)

Help on function cumsum in module numpy:

cumsum(a, axis=None, dtype=None, out=None)
    Return the cumulative sum of the elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        Axis along which the cumulative sum is computed. The default
        (None) is to compute the cumsum over the flattened array.
    dtype : dtype, optional
        Type of the returned array and of the accumulator in which the
        elements are summed.  If `dtype` is not specified, it defaults
        to the dtype of `a`, unless `a` has an integer dtype with a
        precision less than that of the default platform integer.  In
        that case, the default platform integer is used.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output
        but the type will be cast if necessary. See `ufuncs-output-type` for
    

**As an exercise, try to rewrite the remaining part of this part in a concise manner using NumPy, List Comprehension, and looping over a sequence as has been shown above.**\
You'll possibly need to consult with the NumPy references given in the begging of this notebook.

### Screenshot 7-11  - fitting¶

I'll provide comments just to the first (screenshot 7) screenshots, since the remaing are similar.

As already written in the General comments - use arrays with meaningfull names
(here I use plular nouns for variable names - it is more convenient for me)

In [30]:
# Instead of `dist_list`:
distances = ref + np.array(shifts)

distances

array([337.7, 342.7, 347.7, 352.7, 357.7, 358.7, 360.7, 362.7, 364.7,
       366.7, 367.7, 372.7, 377.7, 382.7, 387.7])

In [ ]:
# Since I do not see where `width_list_x` was created, I just convert it to an NumPy array
# (likley `width_list_x` can be created as an array)
peak_widths = np.array(width_list_x)  

In [31]:
# Instead of `ey = [4]*len(width_list)`
# Note: it might be better to call this vaiable 'err_width'
yerr = np.full(len(distances), 4.0)

yerr

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [32]:
yerr.dtype

dtype('float64')

In [33]:
# Another way:
yerr = np.full(len(distances), 4, dtype=float)

yerr

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [34]:
yerr.dtype

dtype('float64')

In [35]:
# Third way (this way uses the same shape and dtype as a given array):
yerr = np.full_like(distances, 4)

yerr

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [ ]:
# Here we use `parabola` name for the fitting function instead of `ff`
par, cov = curve_fit(parabola, distances, peak_widths, sigma=yerr)

**Use unpacking!**

In [ ]:
# Instead of `ff(dist_list,par[0],par[1],par[2])` use `ff(dist_list, *par)`
# (imagine how you would write this if you have 20 parameters)

# Compute chi2:
# (do not pack everything in one line, split in logical steps)
model_peak_widths = parabola(distances, *par)
residuals = model_peak_widths - peak_widths

chi2 = np.sum((residuals / yerr)**2)

In [ ]:
# Compute the number of degrees of freedom
ndof = len(distances) - len(par)

ndof

**Estimate goodness of the fit!**

In [36]:
from scipy import stats

# I directly assign the values here to compute the goodness of the fit
ndof = 12
chi2 = 17.312

# Use Survival function of the `chi2` distribution to compute 
# the probability to have chi2 greater than the obtained one for the given number of degrees of freedom
prob = stats.chi2.sf(chi2, ndof)

prob

0.13823302337992296

So, the probability (=the goodness of fit) is not very good, but quite acceptable.

As I suggested, derive fits using a subset of the points; for example exclude the first and last points:

In [ ]:
distances2 = distances[1: -1]
peak_width2 = peak_widths[1: -1]
yerr2 = yerr[1: -1]

# Better way to slice these arrays
s = slice(1, -1)

distances2 = distances[s]
peak_width2 = peak_widths[s]
yerr2 = yerr[s]

par2, cov2 = curve_fit(parabola, distances2, peak_widths2, sigma=yerr2)

# Even more concise without creating additional arrays 9which are actually 'views'):
s = slice(1, -1)
par2, cov2 = curve_fit(parabola, distances[s], peak_widths[s], sigma=yerr[s])

In [40]:
# What is slice?
s = slice(1, -1)

s

slice(1, -1, None)

In [41]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

In [42]:
a[s]

array([1, 2, 3])

After fitting look at the result, estimate the goodness of fit.

### Summary

* Learn basic of Python and NumPy
* Use basic Python techniques like looping over sequence, unpacking, f-strings, list and dictionary comprehension, etc. 
* Use numpy arrays and a large variety of NumPy/SciPy built-in array methods and functions (instead of trying implement them by yourself from scratch)
* Do NOT use the `math` module (if you use NumPy)
* Do not copy-past code from unreliable internet sources (such code is often old, inefficient or event plainly wrong)
* Try to write clear, consice, efficient, Pythonic(!) code
* Write comments (this is a big separate topic by its own)

Please, read:

In [43]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
